import { RecipeModel } from './models';

export const MOCK_RECIPES: RecipeModel[] = [
  {
    id: 1,
    name: 'قورمه سبزی',
    description: 'خورش کلاسیک ایرانی با سبزیجات معطر، لوبیا قرمز و لیموعمانی.',
    ingredients: [
      { name: 'گوشت خورشتی', quantity: 300, unit: 'گرم' },
      { name: 'سبزی قورمه خردشده', quantity: 400, unit: 'گرم' },
      { name: 'لوبیا قرمز', quantity: 100, unit: 'گرم' },
      { name: 'پیاز', quantity: 2, unit: 'عدد' },
      { name: 'لیموعمانی', quantity: 3, unit: 'عدد' },
      { name: 'روغن مایع', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'زردچوبه', quantity: 1, unit: 'قاشق چای‌خوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 2,
    name: 'خورشت قیمه',
    description: 'خورش محبوب ایرانی با لپه، رب گوجه و سیب‌زمینی سرخ‌شده.',
    ingredients: [
      { name: 'گوشت خورشتی', quantity: 300, unit: 'گرم' },
      { name: 'لپه', quantity: 100, unit: 'گرم' },
      { name: 'پیاز', quantity: 2, unit: 'عدد' },
      { name: 'رب گوجه‌فرنگی', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'لیموعمانی', quantity: 2, unit: 'عدد' },
      { name: 'سیب‌زمینی', quantity: 2, unit: 'عدد' },
      { name: 'زردچوبه', quantity: 1, unit: 'قاشق چای‌خوری' },
      { name: 'دارچین', quantity: 0.5, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 3,
    name: 'زرشک‌پلو با مرغ',
    description: 'پلوی مجلسی با زعفران، زرشک شیرین‌شده و مرغ طلایی.',
    ingredients: [
      { name: 'برنج', quantity: 3, unit: 'پیمانه' },
      { name: 'مرغ', quantity: 4, unit: 'تکه' },
      { name: 'زرشک', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'زعفران دم‌کرده', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'پیاز', quantity: 1, unit: 'عدد' },
      { name: 'کره', quantity: 50, unit: 'گرم' },
      { name: 'شکر', quantity: 1, unit: 'قاشق غذاخوری' },
    ],
  },
  {
    id: 4,
    name: 'کباب کوبیده',
    description: 'کباب اصیل ایرانی از گوشت چرخ‌کرده با عطر زعفران و سماق.',
    ingredients: [
      { name: 'گوشت چرخ‌کرده مخلوط', quantity: 500, unit: 'گرم' },
      { name: 'پیاز', quantity: 1, unit: 'عدد' },
      { name: 'زعفران دم‌کرده', quantity: 1, unit: 'قاشق چای‌خوری' },
      { name: 'سماق', quantity: 1, unit: 'قاشق چای‌خوری' },
      { name: 'کره', quantity: 30, unit: 'گرم' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 5,
    name: 'میرزا قاسمی',
    description: 'پیش‌غذای شمالی با بادمجان کبابی، سیر و گوجه‌فرنگی.',
    ingredients: [
      { name: 'بادمجان', quantity: 4, unit: 'عدد' },
      { name: 'گوجه‌فرنگی', quantity: 4, unit: 'عدد' },
      { name: 'سیر', quantity: 5, unit: 'حبه' },
      { name: 'تخم‌مرغ', quantity: 3, unit: 'عدد' },
      { name: 'روغن زیتون', quantity: 4, unit: 'قاشق غذاخوری' },
      { name: 'زردچوبه', quantity: 0.5, unit: 'قاشق چای‌خوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 6,
    name: 'آش رشته',
    description: 'آش سنتی با حبوبات، سبزی و رشته، همراه با کشک و پیاز داغ.',
    ingredients: [
      { name: 'رشته آش', quantity: 400, unit: 'گرم' },
      { name: 'عدس', quantity: 100, unit: 'گرم' },
      { name: 'نخود', quantity: 100, unit: 'گرم' },
      { name: 'لوبیا چیتی', quantity: 100, unit: 'گرم' },
      { name: 'سبزی آش', quantity: 400, unit: 'گرم' },
      { name: 'کشک', quantity: 2, unit: 'پیمانه' },
      { name: 'پیاز', quantity: 2, unit: 'عدد' },
      { name: 'نعنا خشک', quantity: 2, unit: 'قاشق غذاخوری' },
    ],
  },
  {
    id: 7,
    name: 'خورشت فسنجان',
    description: 'خورش شاهانه گردو و رب انار با طعم ترش و شیرین متعادل.',
    ingredients: [
      { name: 'گردو آسیاب‌شده', quantity: 300, unit: 'گرم' },
      { name: 'رب انار', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'مرغ', quantity: 4, unit: 'تکه' },
      { name: 'پیاز', quantity: 1, unit: 'عدد' },
      { name: 'شکر', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'زعفران دم‌کرده', quantity: 1, unit: 'قاشق چای‌خوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 8,
    name: 'کتلت',
    description: 'کتلت گوشت و سیب‌زمینی با پوسته طلایی و برشته.',
    ingredients: [
      { name: 'گوشت چرخ‌کرده', quantity: 300, unit: 'گرم' },
      { name: 'سیب‌زمینی', quantity: 3, unit: 'عدد' },
      { name: 'پیاز', quantity: 1, unit: 'عدد' },
      { name: 'تخم‌مرغ', quantity: 2, unit: 'عدد' },
      { name: 'آرد سوخاری', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'زردچوبه', quantity: 0.5, unit: 'قاشق چای‌خوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 9,
    name: 'عدس‌پلو',
    description: 'پلوی عدس با کشمش و خرما — شیرین و مقوی.',
    ingredients: [
      { name: 'برنج', quantity: 3, unit: 'پیمانه' },
      { name: 'عدس', quantity: 1, unit: 'پیمانه' },
      { name: 'کشمش', quantity: 100, unit: 'گرم' },
      { name: 'خرما', quantity: 8, unit: 'عدد' },
      { name: 'پیاز', quantity: 1, unit: 'عدد' },
      { name: 'زعفران دم‌کرده', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'کره', quantity: 50, unit: 'گرم' },
    ],
  },
  {
    id: 10,
    name: 'سبزی‌پلو با ماهی',
    description: 'غذای رسمی شب عید؛ پلوی سبزی معطر و ماهی سرخ‌شده.',
    ingredients: [
      { name: 'برنج', quantity: 3, unit: 'پیمانه' },
      { name: 'سبزی پلویی', quantity: 400, unit: 'گرم' },
      { name: 'ماهی سفید', quantity: 4, unit: 'تکه' },
      { name: 'سیر', quantity: 3, unit: 'حبه' },
      { name: 'زعفران دم‌کرده', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'روغن', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 11,
    name: 'املت گوجه‌فرنگی',
    description: 'صبحانه سریع ایرانی؛ تخم‌مرغ و گوجه با عطر طلایی.',
    ingredients: [
      { name: 'گوجه‌فرنگی', quantity: 4, unit: 'عدد' },
      { name: 'تخم‌مرغ', quantity: 4, unit: 'عدد' },
      { name: 'روغن', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
      { name: 'فلفل سیاه', quantity: 0.5, unit: 'قاشق چای‌خوری' },
    ],
  },
  {
    id: 12,
    name: 'باقالی‌پلو با ماهیچه',
    description: 'پلوی باقالی و شوید با ماهیچه نرم و آب‌دار.',
    ingredients: [
      { name: 'برنج', quantity: 3, unit: 'پیمانه' },
      { name: 'باقالی سبز', quantity: 1, unit: 'پیمانه' },
      { name: 'شوید خشک', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'ماهیچه گوسفندی', quantity: 2, unit: 'عدد' },
      { name: 'زعفران دم‌کرده', quantity: 2, unit: 'قاشق غذاخوری' },
      { name: 'روغن', quantity: 3, unit: 'قاشق غذاخوری' },
      { name: 'نمک', quantity: 1, unit: 'قاشق چای‌خوری' },
    ],
  },
];
